name: Run my python
on:
    push:

jobs:
    build:
        name: do job1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
       # - name: Install package
        #  run: |
        #    pip3 install mediapipe
        #- name: Run test.py
        #  run: |
        #    python3 test.py
        - name: Send email
          run: |
            python3 send_mail.py
    build2:
        name: do job2
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2   
        - name: Run test2.py
          run: |
            python3 test2.py
        